### ISSUE TITLE
using bootstrap

### ISSUE THREAD

**Issue by MattKNewell** [MattKNewell/465-565#2]
https://github.com/GoogleCloudPlatform/appengine-guestbook-python

https://cloud.google.com/appengine/docs/standard/python/getting-started/serving-static-files

This is an example project and it has a tutorial that talk about this subject

**Comment by MattKNewell** [comment]
I havent watched this whole thing, but this might be a good solution

https://www.youtube.com/watch?v=PE9ZGniSDW8

**Comment by dannielsotelo** [comment]
Its fixed bro!
