### ISSUE TITLE
Broken Images need to be excluded

### ISSUE THREAD

**Issue by MattKNewell** [MattKNewell/465-565#3]

**Comment by MattKNewell** [comment]
For example:
https://picsum.photos/200/300?image=592

{"error":"Invalid image id"}

**Comment by dannielsotelo** [comment]
Fixed it bro. Check the latest commit. I replaced a broken image with the 0th image.
https://github.com/MattKNewell/465-565/commit/398c18d3919fdff0e96f6bdea14028b6bb771e3d

**Comment by dannielsotelo** [comment]
Now we need to fix duplicate broken images. Image 0 is used multiple times.
